workflow changed

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -29,23 +29,23 @@ jobs:
 
       run: mvn -Dtest=DemoTest test surefire-report:report -Dsurefire.report.format=junit -Dsurefire.report.name=junit/test-results-selenium-${{ matrix.java-version }}
 
-    - name: Test Results Selenium
-      uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
-      with:
-        name: UI tests selenium            # Name of the check run which will be created
-        path: junit/test-results-selenium-${{ matrix.java-version }}.xml    # Path to test results
-
-        reporter: java-junit        # Format of test results
-
-#    - name: Test
-#      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
-#
-#    - name: Report
+#    - name: Test Results Selenium
 #      uses: dorny/test-reporter@v1
-#      if: always()
+#      if: success() || failure()    # run this step even if previous step failed
 #      with:
-#        name: Maven Tests
-#        path: target/surefire-reports/*.xml
-#        reporter: java-junit
-#        fail-on-error: true
+#        name: UI tests selenium            # Name of the check run which will be created
+#        path: junit/test-results-selenium-${{ matrix.java-version }}.xml    # Path to test results
+#
+#        reporter: java-junit        # Format of test results
+
+    - name: Test
+      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
+
+    - name: Report
+      uses: dorny/test-reporter@v1
+      if: always()
+      with:
+        name: Maven Tests
+        path: target/surefire-reports/*.xml
+        reporter: java-junit
+        fail-on-error: true
