workflow changed

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -30,21 +30,28 @@ jobs:
       uses: actions/setup-java@v3
       with:
         java-version: ${{ matrix.java-version }}
-#        distribution: 'temurin'
         cache: maven
-    - name: Build with Maven
-#      run: mvn test --file pom.xml
-#      run: mvn -Dtest=DemoTest test
-      run: mvn -Dtest=DemoTest test surefire-report:report -Dsurefire.report.format=junit -Dsurefire.report.name=junit/test-results-selenium-${{ matrix.java-version }}
-#      run: pytest tests/functional_tests/demo_test.py --doctest-modules --junitxml=junit/test-results-selenium-${{ matrix.python-version }}.xml
+#    - name: Build with Maven
+#
+#      run: mvn -Dtest=DemoTest test surefire-report:report -Dsurefire.report.format=junit -Dsurefire.report.name=junit/test-results-selenium-${{ matrix.java-version }}
+#
+#    - name: Test Results Selenium
+#      uses: dorny/test-reporter@v1
+#      if: success() || failure()    # run this step even if previous step failed
+#      with:
+#        name: UI tests selenium            # Name of the check run which will be created
+#        path: junit/test-results-selenium-${{ matrix.java-version }}.xml    # Path to test results
+#
+#        reporter: java-junit        # Format of test results
 
-    - name: Test Results Selenium
-      uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
-      with:
-        name: UI tests selenium            # Name of the check run which will be created
-#        path: target/surefire-reports/junit/test-results-selenium-${{ matrix.java-version }}.xml    # Path to test results
-        path: junit/test-results-selenium-${{ matrix.java-version }}.xml    # Path to test results
+        - name: Test
+            run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
 
-        reporter: java-junit        # Format of test results
-
+            - name: Report
+              uses: dorny/test-reporter@v1
+              if: always()
+              with:
+                name: Maven Tests
+                path: target/surefire-reports/*.xml
+                reporter: java-junit
+                fail-on-error: true
